### ISSUE TITLE
Test WebWallet in DEVNET-1 (Comos-SDK v0.50.x)

### ISSUE THREAD

**Issue by RaulBernal** [BitCannaGlobal/BCNA#442]
### TXs operations
- [X] Send: https://explorer-devnet-6.bitcanna.io/bitcanna-dev1/tx/5A7A3C5EAC267B97A590359ACFA3F6F12EC8089A01BECC5CDB00FB7C9F2ED7B5
- [x] Claim rewards: (23) https://explorer-devnet-6.bitcanna.io/bitcanna-dev1/tx/4CDF03FC4061C9B9343BB9182DF4FFF4D05C431F389EEA87F08CD9F7E01024B0 
- [X] Delegate: https://explorer-devnet-6.bitcanna.io/bitcanna-dev1/tx/6E347B946ED9755D06C914E0E8802A3BB412754D14D6B670EA82370312A79C36
- [x] Undelegate: https://explorer-devnet-6.bitcanna.io/bitcanna-dev1/tx/98A8CEB948CA0DDE317C5DE5C38F13B4B963A8458640FB7521B5E1516118B8BE
- [x] Redelegate: https://explorer-devnet-6.bitcanna.io/bitcanna-dev1/tx/13E9BB764753115D5F04824A59BD0D0FA12ED49484D1FE14A19AF663DCC906B4
- [x] Vote on proposals:  **FIXED** https://github.com/BitCannaGlobal/bcna/issues/442#issuecomment-2375301831
   - [x] FAIL: OLD proposal not showing (FIXED)
   - [X]  TESTED: Autocalculated gas could be lower than needed, but it's ok respectively to v0.50 migration
  Console error:
```js
entry.051749d3.js:1 TypeError: Cannot read properties of undefined (reading 'title')
    at index.05e98144.js:10:1940
    at Array.forEach (<anonymous>)
    at Proxy.mounted (index.05e98144.js:10:1877)
logError @ entry.051749d3.js:1Understand this error
8entry.051749d3.js:47 SpendableBalances 208641406.9139
``` 

TX proposal: https://explorer-devnet-6.bitcanna.io/bitcanna-dev1/tx/2DA74EFA83A23CA76C5C943D098375E33F39846317FB643722D5F943BB0EA11E

### Info retrieved/shown
- [x] MAIN: Balances: OK
- [x] MAIN: Cards with Delegations/Rewards: OK
- [x] MAIN: Transactions:  **FIXED** https://github.com/BitCannaGlobal/bcna/issues/442#issuecomment-2375306851
![Image](https://github.com/user-attachments/assets/38248264-e9f8-44a9-8e41-a273a908a6f0)

### After send a TX
- [X] After Claim all rewards doesn't show the Confirmation Screen
![Image](https://github.com/user-attachments/assets/0a6222bd-a819-4559-8d87-0c881d789747)
```js
ClaimAllModal.af3ec30e.js:1 Error: Invalid string. Length must be a multiple of 4
    at getLens (entry.051749d3.js:45:147578)
    at Object.toByteArray (entry.051749d3.js:45:147855)
    at fromBase64 (entry.051749d3.js:45:150019)
    at decodeAttribute (entry.051749d3.js:47:911750)
    at Array.map (<anonymous>)
    at decodeAttributes$1 (entry.051749d3.js:47:911942)
    at decodeEvent$1 (entry.051749d3.js:47:912032)
    at Array.map (<anonymous>)
    at decodeEvents$1 (entry.051749d3.js:47:912173)
    at decodeTxData$1 (entry.051749d3.js:47:912414)
```
Fixed here https://github.com/BitCannaGlobal/WeedWallet/commit/6e99a45b99fc6996f6b75b496c2780f2c80f30de#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R26
bumping CosmJS version to latest that support CometBFT v0.38.x

**Comment by RaulBernal** [comment]
Proposal page fixed here: https://github.com/BitCannaGlobal/WeedWallet/commit/cd159c1e7061ee3fc7c2ab2fe324e7aaa360ab3f

New Proposals should use the main "title" and "summary" fields. This fix keeps legacy proposal still showing.

**Comment by RaulBernal** [comment]
Transactions page and main page listing of TX fixed here: https://github.com/BitCannaGlobal/WeedWallet/commit/a31b4677787cf012069966982127392f9f7e4468

LCD Queries for  `/txs/` endpoint (query events in the TXs)  should use `query` field in place of `events`

**Comment by RaulBernal** [comment]
`devnet-1` branch should be merged into `main` when we upgrade MainNET to v0.50
